capture: fix typo in FILE object
FILE *fstdin is defined, but when calling freopen() stdin is used instead
of fstdin.

This causes the compile to fail:

  CC       sngrep-capture.o
capture.c: In function 'capture_offline':
capture.c:194:21: error: assignment of read-only variable 'stdin'
         if (!(stdin = freopen("/dev/tty", "r", stdin))) {
                     ^
make[5]: *** [Makefile:519: sngrep-capture.o] Error 1

This commit fixes the typo.

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>